#!/bin/sh
# firewall
# antonioneris@gmail.com
# Descrição : Starta o Firewall Iptables com suas propriedades liberadas

echo "Script que libera as portas de uso do Zimbra versao 8.7"

case "$1" in
	# Iniciando Servido de Firewall
	"start")
		# Clear rules
		iptables -t filter -F
		iptables -t filter -X
		echo -- Clear rules : [OK]

		# Create a reject-and-log-SSH-Bruteforce chain to forward things to.

		iptables -N REJECT-SMTP
		iptables -A REJECT-SMTP -s 179.104.44.255 -j ACCEPT
		iptables -A REJECT-SMTP -j DROP -m recent --rcheck --name SMTP --seconds 60 --hitcount 30
		iptables -A REJECT-SMTP -j LOG --log-prefix "SMTP Brute-force"
		iptables -A REJECT-SMTP -j REJECT -p tcp --reject-with tcp-reset
		iptables -A REJECT-SMTP -j REJECT

		# Kill SSH brute-force attacks. Allow only three connections per minute
		# from any source.

		iptables -A INPUT -p tcp --dport 587 -m state --state NEW -m recent --update --name SMTP --seconds 60 --hitcount 25 -j REJECT-SMTP
		iptables -A INPUT -p tcp --dport 587 -m state --state NEW -m recent --set --name SMTP
		iptables -A INPUT -p tcp --dport 465 -m state --state NEW -m recent --update --name SMTP --seconds 60 --hitcount 25 -j REJECT-SMTP
                iptables -A INPUT -p tcp --dport 465 -m state --state NEW -m recent --set --name SMTP
		echo "-- SMTP Protection [OK]"

		# SYN-Flood Protection
                iptables -N syn-flood
                iptables -A syn-flood -j LOG --log-prefix "SYN FLOOD: "
                iptables -A syn-flood -m limit --limit 5/second --limit-burst 10 -j RETURN
                iptables -A syn-flood -j DROP
                echo "-- SYN-Flood Protection : [OK]"


		#Drops
		iptables -A INPUT -s 187.95.127.107 -j DROP
		#iptables -A INPUT -s 191.251.198.127 -j DROP
		iptables -A INPUT -s 201.93.202.252 -j DROP
		#iptables -A INPUT -s 177.102.239.46 -j DROP
		#iptables -A INPUT -s 189.5.225.203 -j DROP
		#iptables -A INPUT -s 200.214.152.22 -j DROP
		#iptables -A INPUT -s 168.0.96.3 -j DROP
		#iptables -A INPUT -s 186.231.146.222 -j DROP
		iptables -A INPUT -s 54.162.159.54 -j DROP
		#iptables -A INPUT -s 54.94.241.13 -j DROP
		#iptables -A INPUT -s 189.121.47.118 -j DROP
		#iptables -A INPUT -s 52.67.178.57 -j DROP
		#iptables -A INPUT -s 54.94.232.75 -j DROP
		#iptables -A INPUT -s 54.94.253.51 -j DROP
		#iptables -A INPUT -s 54.94.242.130 -j DROP
		#iptables -A INPUT -s 54.94.252.245 -j DROP
		#iptables -A INPUT -s 177.235.176.150 -j DROP

		echo "-- DROPs de IPs [OK]"

		# SSH In
		iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
		echo -- SSH : [OK]

		# Criando Regras de Logs
		#iptables -t filter -A OUTPUT -p tcp --dport 80 -j LOG --log-prefix "OUTPUT Porta 80 :"
		#iptables -t filter -A OUTPUT -p tcp --dport 443 -j LOG --log-prefix "OUTPUT Porta 443 :"
		#echo "-- LOG de Saida portas 80 e 443 : [OK]"

		#iptables -t filter -A INPUT -p tcp --dport 80 -j LOG --log-prefix "INPUT Porta 80 :"
		#iptables -t filter -A INPUT -p tcp --dport 443 -j LOG --log-prefix "INPUT Porta 443 :"
		#echo "-- LOG de Entrada portas 80 e 443 : [OK]"

		#iptables -t filter -A INPUT -p tcp --dport 25 -j LOG --log-prefix "INPUT Porta 25 :"
		#iptables -t filter -A OUTPUT -p tcp --dport 25 -j LOG --log-prefix "OUTPUT Porta 25 :"
		#echo "-- LOG de Entrada e Saida portas 25 : [OK]"

		#iptables -t filter -A INPUT -p tcp --dport 587 -j LOG --log-prefix "INPUT Porta 587 :"
		#echo "-- LOG de Entrada portas 587 : [OK]"


		# Mantendo as conexes ativas
		iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
		iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
		echo "-- Mantenddo Conexoes Ativas : [OK]"

		# Bloqueando todas as conexoes por padrao
		iptables -t filter -P INPUT DROP
		iptables -t filter -P FORWARD DROP
		iptables -t filter -P OUTPUT DROP
		echo "-- Bloqueando todas as Conexoes (Police DROP INPUT,FORWARD e OUTPUT) : [OK]"

		# SYN-Flood Protection
		#iptables -N syn-flood
		#iptables -A syn-flood -j LOG --log-prefix "SYN FLOOD: "
		#iptables -A syn-flood -m limit --limit 10/second --limit-burst 50 -j RETURN
		#iptables -A syn-flood -j DROP
		#echo "-- SYN-Flood Protection : [OK]"

		# Loopback
		iptables -t filter -A INPUT -i lo -j ACCEPT
		iptables -t filter -A OUTPUT -o lo -j ACCEPT
		echo "-- Loopback : [OK]"

		# ICMP (Ping)
		iptables -t filter -A INPUT -p icmp -j ACCEPT
		iptables -t filter -A OUTPUT -p icmp -j ACCEPT
		echo "-- PING : [OK]"

		# DNS In/Out
		iptables -t filter -A OUTPUT -p tcp --dport 53 -j ACCEPT
		iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT
		iptables -t filter -A INPUT -p tcp --dport 53 -j ACCEPT
		iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT
		echo "-- DNS : [OK]"

		# NTP Out
		iptables -t filter -A OUTPUT -p udp --dport 123 -j ACCEPT
		echo "-- NTP : [OK]"

		# HTTP + HTTPS Out
		iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT
		
		# HTTP + HTTPS In
		iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
		iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
		
		echo "-- HTTP/HTTPS Entrada e Saida : [OK]"

		# Mail SMTP:25
		iptables -t filter -A INPUT -p tcp --dport 25 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 25 -j ACCEPT
		
		echo "-- SMTP Input/Output 25 : [OK]"

		# Mail SMTP : 587
		iptables -t filter -A INPUT -p tcp --dport 587 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 587 -j ACCEPT
		
		echo "-- SMTP Input/Output 587 : [OK]"

		# Mail POP3:110
		iptables -t filter -A INPUT -p tcp --dport 110 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 110 -j ACCEPT
		echo "-- POP Input/Output 110 : [OK]"

		# Mail IMAP:143
		iptables -t filter -A INPUT -p tcp --dport 143 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 143 -j ACCEPT
		echo "-- IMAP Input/Output 143 : [OK]"

		# Mail IMAP:443
		iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT
		echo "-- HTTPS Input/Output 443 : [OK]"

		# Mail IMAPS:993
		iptables -t filter -A INPUT -p tcp --dport 993 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 993 -j ACCEPT
		echo "-- IMAPS Input/Outpuy 993 : [OK]"

		# Mail POP3S:995
		iptables -t filter -A INPUT -p tcp --dport 995 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 995 -j ACCEPT
		echo "-- POP3S Input/Output 995: [OK]"

		# SOAP Auth 7073
		iptables -t filter -A INPUT -p tcp --dport 7073 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 7073 -j ACCEPT
		echo "-- SOAP Auth 7073 : [OK]"

		# Mail ZIMBRA ADMIN:7071
		iptables -t filter -A INPUT -p tcp --dport 7071 -j ACCEPT
		iptables -t filter -A OUTPUT -p tcp --dport 7071 -j ACCEPT
		echo -- ACESSO ADMIN ZIMBRA 7071: [OK]

		# Mail ZIMBRA ADMIN:7025
    iptables -t filter -A INPUT -p tcp --dport 7025 -j ACCEPT
    iptables -t filter -A OUTPUT -p tcp --dport 7025 -j ACCEPT
    echo -- ACESSO ADMIN ZIMBRA 7025: [OK]

		# Mail ZIMBRA ADMIN:8443
    iptables -t filter -A INPUT -p tcp --dport 8443 -j ACCEPT
    iptables -t filter -A OUTPUT -p tcp --dport 8443 -j ACCEPT
    echo -- ACESSO ADMIN ZIMBRA 8443: [OK]
    echo -- Firewall Ativado [OK]


	;;

	# Parando Servico de Firewall
	"stop")
		echo "Parando Firewall…"
		iptables -P INPUT ACCEPT
		echo "Reset INPUT" : [OK]
		iptables -P OUTPUT ACCEPT
		echo "Reset OUTPUT" : [OK]
		iptables -t filter -F
		echo "Reset Filter" :[OK]
		echo "Firewall Parado com Sucesso!"
	;;

	# Restartando o Sevico de Firewall
	"restart")
		echo "Reiniciando Servico de Firewall"
		/etc/init.d/firewall stop
		/etc/init.d/firewall start
	;;

	*) 
		echo $"Favor usar conforme a Syntax: $0 {start|stop|restart}"
esac
